# Generated by Django 2.2.7 on 2022-03-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfDownload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
